# Fraud-u-not ML Model Training

### Import Libaries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Import Dataset

In [3]:
fraudData = pd.read_csv('./card_transdata.csv')

fraudData

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999998,4.258729,0.242023,0.475822,1.0,0.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

### Null value checks

In [4]:
print("Null values:")
fraudData.isnull().sum()

Null values:

distance_from_home                0
distance_from_last_transaction    0
ratio_to_median_purchase_price    0
repeat_retailer                   0
used_chip                         0
used_pin_number                   0
online_order                      0
fraud                             0
dtype: int64

### Data Exploration

In [5]:
print("percentage of fraud: ", fraudData['fraud'].value_counts().loc[1.0]  /  fraudData.shape[0] * 100)

fraudData['fraud'].value_counts()

percentage of fraud:  8.7403

0.0    912597
1.0     87403
Name: fraud, dtype: int64

In [6]:
fraudData.describe()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,26.628792,5.036519,1.824182,0.881536,0.350399,0.100608,0.650552,0.087403
std,65.390784,25.843093,2.799589,0.323157,0.477095,0.300809,0.476796,0.282425
min,0.004874,0.000118,0.004399,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.878008,0.296671,0.475673,1.000000,0.000000,0.000000,0.000000,0.000000
50%,9.967760,0.998650,0.997717,1.000000,0.000000,0.000000,1.000000,0.000000
75%,25.743985,3.355748,2.096370,1.000000,1.000000,0.000000,1.000000,0.000000
max,10632.723672,11851.104565,267.802942,1.000000,1.000000,1.000000,1.000000,1.000000

##### Catergory Fraud effect

In [18]:
catergoryFraudData = pd.DataFrame(index=['Did Not', 'Did', 'Perc Change'])

for c in fraudData.columns:
    if fraudData[c].nunique() <= 2 and c != 'fraud':
        
        fraudMean0 = fraudData.loc[fraudData[c] == 0, 'fraud'].mean()
        fraudMean1 = fraudData.loc[fraudData[c] == 1, 'fraud'].mean()
        
        change = (max(fraudMean1, fraudMean0)- min(fraudMean1, fraudMean0)) / min(fraudMean1, fraudMean0) * 100
        change= str(round(change, 2)) + "%"
        catergoryFraudData[c] = [fraudMean0, fraudMean1, change]
    
catergoryFraudData

            repeat_retailer  used_chip used_pin_number online_order
Did Not           0.0884488   0.100051       0.0968766    0.0134269
Did               0.0872625  0.0639557       0.0027135      0.12714
Perc Change           1.36%     56.44%        3470.17%       846.9%

##### Numeric Fraud Effect